name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}-v2
      - name: Install Vercel CLI
        run: bun install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: url="$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})" && vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" fbla-job-portal
